### ISSUE TITLE
Form Validator needs Swing changes for Mac

### ISSUE THREAD

**Issue by dcbriccetti** [opendatakit/validate#30]
Notice when running on a Mac that the title shows as AppMain.

![screen shot 2017-04-08 at 11 21 50 am](https://cloud.githubusercontent.com/assets/55099/24831400/a0330d5e-1c4d-11e7-8fb8-5b2890752e71.png)

“Do the needful” to make this Swing application Mac friendly. It’s pretty simple.

https://www.google.com/search?q=java+swing+mac

**Comment by lognaturel** [comment]
Deemed not worth the effort in Briefcase.
