### ISSUE TITLE
Make UI look more like a modern Java app

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/validate#48]
ODK Briefcase looks like this:
<img width="597" alt="briefcase" src="https://user-images.githubusercontent.com/32369/35251306-7a933904-ff8f-11e7-9b1d-1ed4bb571116.png">
Note the grey buttons and clean lines.

ODK Validate looks like this:
<img width="861" alt="validate" src="https://user-images.githubusercontent.com/32369/35251305-7a79e332-ff8f-11e7-8b8b-9f292510871d.png">
Note the blue buttons and gradients.

It would be good if the UI of Validate was updated so it looked more like a modern Java app.

**Comment by vigneshtdev** [comment]
Hi, I would like to fix this issue. Would you like the changes to be made to the styling of swing components or would you like a rebuilding the whole thing with javafx?

**Comment by yanokwa** [comment]
Hi! I think given that this is a small app, it might be good to experiment and try to make it JavaFx.

**Comment by batkinson** [comment]
Hey,

I think the reason for the difference is that Validate doesn't use the
native look and feel and instead uses the Swing default one. You should not
have to do anything other than remove the bits of code explicitly setting
the native look and feel. It has nothing to do with JavaFx. I seem to
remember recent issues dealing with the native look and feel, so just
beware that this was done intentionally by someone. You might want to dig
into why before making the change, but trying it should be easy.

Regards,

Brent
