### ISSUE TITLE
Remove "See above for the errors"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/validate#88]
There are two messages that say "See above for the errors":

https://github.com/getodk/validate/blob/79204416473845e3afa25074f47de67982d2d194/src/org/opendatakit/validate/FormValidator.java#L514

https://github.com/getodk/validate/blob/79204416473845e3afa25074f47de67982d2d194/src/org/opendatakit/validate/FormValidator.java#L435

The messages are printed out:
https://github.com/getodk/validate/blob/master/src/org/opendatakit/validate/ErrorListener.java#L16

I believe the errors will always be **below**.

I think we should remove "See above for the errors" instead of changing it to "below" because it doesn't add anything.

**Comment by yuhaoban** [comment]
Hi @lognaturel, could I contribute on this issue as a beginning? Thanks!
